spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5435/order_service}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=${APP_PORT:8080}
#8083

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:db/changeSet/changelog-master.yaml

resilience4j.circuitbreaker.instances.userServiceBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.userServiceBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.userServiceBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.userServiceBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.userServiceBreaker.waitDurationInOpenState=10s
user-service.base-url=http://localhost:8082

jwt.secret=${JWT_SECRET}