server.port=${APP_PORT:8083}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

user-service.base-url=${USER_SERVICE_URL}

jwt.secret=${JWT_SECRET}